services:
  boilerplate_service:
    build:
      dockerfile: Dockerfile
      context: .
      # build development stage only from dockerfile
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    # Run a command against the development stage of the image
    command: npm run start:dev
    ports:
      - ${PORT}:${PORT}
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: redis-server --requirepass "redis_password"
    networks:
      - backend
    volumes:
      - redis_data:/data

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - 5432:5432
    networks:
      - backend
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  backend:
    driver: bridge

volumes:
  redis_data:
    driver: local
  db_data:
    driver: local
