export interface ICommonException {
  /**
   * "A URI reference that identifies the problem type."
   * "https://example.net/validation-error"
   */
  type?: string;
  /**
   * "A short, human-readable summary of the problem type."
   * "Your request is not valid."
   */
  title: string;
  /**
   * "The HTTP status code generated by the origin server for this occurrence of the problem."
   * "minimum": 400, "maximum": 599
   */
  status: number;
  /**
   * "A human-readable explanation specific to this occurrence of the problem."
   */
  detail?: string;

  /**
   * "A human-readable timestamp in ISO format."
   */
  timestamp?: string;
}
